- name: Install additional software
  hosts: windows
  vars_files:
    - "../software_links.yml"

  tasks:
    - name: Create installer directory
      win_file:
        path: "{{ ansible_env.USERPROFILE }}\\Downloads\\installs"
        state: directory

    - name: Copy all install files from WSL to Windows Downloads folder
      win_copy:
        src: "../../installs/"
        dest: "{{ ansible_env.USERPROFILE }}\\Downloads\\installs"
        remote_src: false
      ignore_errors: true  # To continue even if some files fail to copy

    - name: Download installers
      win_get_url:
        url: "{{ item.url }}"
        dest: "{{ ansible_env.USERPROFILE }}\\Downloads\\installs\\{{ item.filename }}"
      loop: "{{ software_list }}"
      register: download_status
      ignore_errors: true  # To continue even if some files fail to copy

    - name: Install software via MSI
      win_package:
        path: "{{ ansible_env.USERPROFILE }}\\Downloads\\installs\\{{ item.filename }}"
        state: present
        arguments: "{{ item.silent_args }}"
      loop: "{{ software_list }}"
      when: item.install_method == 'msi'
      register: msi_install_status
      ignore_errors: true  # To continue even if some files fail to copy

    - name: Install software via EXE
      win_shell: "Start-Process -FilePath '{{ ansible_env.USERPROFILE }}\\Downloads\\installs\\{{ item.filename }}' -ArgumentList '{{ item.silent_args }}' -Wait"
      args:
        chdir: "{{ ansible_env.USERPROFILE }}\\Downloads\\installs"
      loop: "{{ software_list }}"
      when: item.install_method == 'exe'
      register: exe_install_status
      ignore_errors: true  # To continue even if some files fail to copy

    - name: Display installation results
      debug:
        msg: 
          - "Downloaded: {{ download_status.results | selectattr('changed') | list | length }} items"
          - "MSI Installed: {{ msi_install_status.results | selectattr('changed') | list | length }} items"
          - "EXE Installed: {{ exe_install_status.results | selectattr('changed') | list | length }} items"
