#!/usr/bin/env bash
# setup-cao.sh — CAO Installation Script
# Sets up CLI Agent Orchestrator (CAO) in WSL2 for use with Windows Antigravity.
#
# What this does:
#   1. Installs cli-agent-orchestrator via pip
#   2. Creates the agy wrapper script (~/.local/bin/agy)
#   3. Applies the WSL-to-Windows MCP bridge patch to antigravity_cli.py
#   4. Writes the CAO settings.json (disables CAO memory to avoid conflict with Omnigraph)
#   5. Configures CAO_HOME_DIR in ~/.bashrc
#   6. Registers cao-ops MCP server in ~/.gemini/config/mcp_config.json (if writable)
#   7. Starts cao-server in the background
#
# Usage (from repo root inside WSL2 Ubuntu):
#   bash infra/mcp-servers/cao-setup/setup-cao.sh
#   bash infra/mcp-servers/cao-setup/setup-cao.sh --check   # Health-check only, no changes
#
# Requirements:
#   - WSL2 Ubuntu (or compatible)
#   - python3 + pip accessible in $PATH
#   - Windows agy.exe at /mnt/c/Users/<user>/AppData/Local/agy/bin/agy.exe
#     (override with: AGY_EXE_WIN_PATH="..." bash setup-cao.sh)

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECK_ONLY=false
if [[ "${1:-}" == "--check" ]]; then CHECK_ONLY=true; fi

# ─── Config ───────────────────────────────────────────────────────────────────
CAO_VERSION="${CAO_VERSION:-cli-agent-orchestrator}"          # pip spec; pin with ==x.y.z
CAO_HOME_DIR="${CAO_HOME_DIR:-$HOME/.cao}"
WSL_DISTRO="${WSL_DISTRO_NAME:-Ubuntu}"

# Detect Windows username from /mnt/c/Users/
WINDOWS_USER="${WINDOWS_USER:-}"
if [[ -z "$WINDOWS_USER" ]]; then
  WINDOWS_USER="$(ls /mnt/c/Users/ 2>/dev/null | grep -v -E '^(Public|Default|All Users)$' | head -1)"
fi
AGY_EXE_WIN_PATH="${AGY_EXE_WIN_PATH:-/mnt/c/Users/${WINDOWS_USER}/AppData/Local/agy/bin/agy.exe}"
GEMINI_CONFIG="${GEMINI_CONFIG:-$HOME/.gemini/config}"

# ─── Helpers ──────────────────────────────────────────────────────────────────
ok()   { echo "[OK]   $*"; }
info() { echo "[INFO] $*"; }
warn() { echo "[WARN] $*"; }
fail() { echo "[FAIL] $*" >&2; exit 1; }
sep()  { echo "────────────────────────────────────────"; }

# ─── Health Check ─────────────────────────────────────────────────────────────
run_check() {
  sep
  echo "CAO Health Check"
  sep

  # 1. CAO package
  if python3 -c "import cli_agent_orchestrator" 2>/dev/null; then
    VER="$(python3 -c "import importlib.metadata; print(importlib.metadata.version('cli-agent-orchestrator'))" 2>/dev/null || echo "unknown")"
    ok "cli-agent-orchestrator $VER installed"
  else
    warn "cli-agent-orchestrator NOT installed"
  fi

  # 2. WSL bridge patch
  if python3 -c "
import cli_agent_orchestrator.providers.antigravity_cli as m, inspect, pathlib
src = pathlib.Path(inspect.getfile(m)).read_text()
assert 'WSL to Windows cross-environment bridge' in src
" 2>/dev/null; then
    ok "WSL bridge patch applied"
  else
    warn "WSL bridge patch NOT applied — run setup-cao.sh to apply"
  fi

  # 3. agy wrapper
  if [[ -x "$HOME/.local/bin/agy" ]]; then
    ok "agy wrapper found at ~/.local/bin/agy"
  else
    warn "agy wrapper missing at ~/.local/bin/agy"
  fi

  # 4. cao-server
  if curl -fsS "http://localhost:9889/health" >/dev/null 2>&1; then
    ok "cao-server responding at :9889"
  else
    warn "cao-server NOT responding at :9889 (start with: cao-server &)"
  fi

  # 5. Memory disabled in settings
  if [[ -f "$CAO_HOME_DIR/settings.json" ]] && python3 -c "
import json, pathlib
s = json.loads(pathlib.Path('$CAO_HOME_DIR/settings.json').read_text())
assert s.get('memory', {}).get('enabled') == False
" 2>/dev/null; then
    ok "CAO memory disabled (Omnigraph is the memory layer)"
  else
    warn "CAO memory not disabled — agents may use conflicting memory tools"
  fi

  sep
}

if $CHECK_ONLY; then
  run_check
  exit 0
fi

# ─── 1. Install CAO ───────────────────────────────────────────────────────────
sep
info "Step 1/7: Installing cli-agent-orchestrator"
pip install --quiet --user "$CAO_VERSION"
export PATH="$HOME/.local/bin:$PATH"
VER="$(python3 -c "import importlib.metadata; print(importlib.metadata.version('cli-agent-orchestrator'))" 2>/dev/null || echo "unknown")"
ok "Installed cli-agent-orchestrator $VER"

# ─── 2. agy wrapper ───────────────────────────────────────────────────────────
sep
info "Step 2/7: Creating agy wrapper script"
mkdir -p "$HOME/.local/bin"

if [[ ! -f "$AGY_EXE_WIN_PATH" ]]; then
  warn "agy.exe not found at $AGY_EXE_WIN_PATH"
  warn "Edit AGY_EXE_WIN_PATH= and re-run, or create the wrapper manually."
else
  cat > "$HOME/.local/bin/agy" <<EOF
#!/usr/bin/env bash
# Auto-generated by setup-cao.sh — calls Windows agy.exe from WSL2
exec "${AGY_EXE_WIN_PATH}" "\$@"
EOF
  chmod +x "$HOME/.local/bin/agy"
  ok "agy wrapper created at ~/.local/bin/agy"
fi

# ─── 3. WSL bridge patch ──────────────────────────────────────────────────────
sep
info "Step 3/7: Applying WSL-to-Windows MCP bridge patch"
bash "$SCRIPT_DIR/patches/apply_wsl_bridge_patch.sh"

# ─── 4. CAO settings (disable built-in memory) ───────────────────────────────
sep
info "Step 4/8: Writing ~/.cao/settings.json (disabling CAO memory tool)"
mkdir -p "$CAO_HOME_DIR"
cat > "$CAO_HOME_DIR/settings.json" <<'EOF'
{
  "_comment": "Managed by setup-cao.sh — do not edit manually.",
  "memory": {
    "enabled": false,
    "_reason": "Omnigraph (not CAO memory) is the canonical project memory layer per AGENTS.md. Disabling prevents agents from being confused between two competing memory tools."
  },
  "cleanup": {
    "auto_cleanup_enabled": false,
    "_reason": "User must be able to inspect agent sessions in the web dashboard. Manual cleanup only: `cao terminal delete <id>`."
  }
}
EOF
ok "settings.json written — CAO memory disabled, auto-cleanup disabled"

# ─── 5. Install custom agent profiles ───────────────────────────────────────
sep
info "Step 5/8: Installing custom agent profiles (memory disabled)"
PROFILES_SRC="$SCRIPT_DIR/profiles"
AGENT_STORE="$CAO_HOME_DIR/agent-store"
mkdir -p "$AGENT_STORE"
for profile_file in "$PROFILES_SRC"/*.md; do
  [[ -f "$profile_file" ]] || continue
  basename_file="$(basename "$profile_file")"
  cp "$profile_file" "$AGENT_STORE/$basename_file"
  ok "Installed profile: $basename_file"
done

# ─── 6. CAO_HOME_DIR in ~/.bashrc ────────────────────────────────────────────
sep
info "Step 6/8: Adding CAO_HOME_DIR to ~/.bashrc"
MARKER="# CAO setup — added by setup-cao.sh"
if grep -q "$MARKER" "$HOME/.bashrc" 2>/dev/null; then
  info "CAO_HOME_DIR already in ~/.bashrc (skipping)"
else
  cat >> "$HOME/.bashrc" <<EOF

$MARKER
export CAO_HOME_DIR="$CAO_HOME_DIR"
export PATH="\$HOME/.local/bin:\$PATH"
EOF
  ok "Added CAO_HOME_DIR export to ~/.bashrc"
fi

# ─── 6. Register cao-ops in mcp_config.json ──────────────────────────────────
sep
info "Step 7/8: Registering cao-ops MCP server"
MCP_CONFIG="$GEMINI_CONFIG/mcp_config.json"
mkdir -p "$GEMINI_CONFIG"

if [[ -f "$MCP_CONFIG" ]]; then
  # Check if already registered
  if python3 -c "import json; d=json.load(open('$MCP_CONFIG')); assert 'cao-ops' in d.get('mcpServers',{})" 2>/dev/null; then
    info "cao-ops already registered in $MCP_CONFIG (skipping)"
  else
    python3 - <<PYEOF
import json, pathlib

path = pathlib.Path("$MCP_CONFIG")
cfg = json.loads(path.read_text()) if path.stat().st_size > 0 else {}
servers = cfg.setdefault("mcpServers", {})
servers["cao-ops"] = {
    "command": "wsl",
    "args": [
        "-d", "$WSL_DISTRO",
        "bash", "-c",
        'export PATH="\$HOME/.local/bin:\$PATH"; export CAO_HOME_DIR="$CAO_HOME_DIR"; cao-ops-mcp-server'
    ]
}
tmp = path.with_suffix(".json.tmp")
tmp.write_text(json.dumps(cfg, indent=2))
tmp.rename(path)
print("[OK]   cao-ops registered in $MCP_CONFIG")
PYEOF
  fi
else
  cat > "$MCP_CONFIG" <<EOF
{
  "mcpServers": {
    "cao-ops": {
      "command": "wsl",
      "args": [
        "-d", "${WSL_DISTRO}",
        "bash", "-c",
        "export PATH=\\"\\$HOME/.local/bin:\\$PATH\\"; export CAO_HOME_DIR=\\"${CAO_HOME_DIR}\\"; cao-ops-mcp-server"
      ]
    }
  }
}
EOF
  ok "Created $MCP_CONFIG with cao-ops entry"
fi

# ─── 7. Start cao-server ─────────────────────────────────────────────────────
sep
info "Step 8/8: Starting cao-server"
if curl -fsS "http://localhost:9889/health" >/dev/null 2>&1; then
  ok "cao-server already running at :9889"
else
  export CAO_HOME_DIR="$CAO_HOME_DIR"
  nohup cao-server > "$CAO_HOME_DIR/logs/cao-server.log" 2>&1 &
  sleep 3
  if curl -fsS "http://localhost:9889/health" >/dev/null 2>&1; then
    ok "cao-server started (pid $!) — dashboard: http://localhost:9889"
  else
    warn "cao-server may still be starting — check: curl http://localhost:9889/health"
    warn "Log: $CAO_HOME_DIR/logs/cao-server.log"
  fi
fi

# ─── Done ─────────────────────────────────────────────────────────────────────
sep
echo ""
echo "CAO setup complete!"
echo ""
echo "Next steps:"
echo "  source ~/.bashrc"
echo "  cao profile list               # verify profiles"
echo "  cao workflow validate <file>   # validate a workflow spec"
echo "  # Restart Antigravity IDE to pick up the new cao-ops MCP server"
echo ""
run_check
